---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Create SSL key directory
      file:
        path: /etc/ssl/private
        state: directory
    - name: Copy SSL Key file
      copy:
        src: hostname.key.vault
        dest: /etc/ssl/private/unplatform.mit.edu.key
        mode: 0600
    - name: Copy SSL Cert file
      copy:
        src: hostname.crt.vault
        dest: /etc/ssl/certs/unplatform.mit.edu.crt
    - name: Copy intermediate chain file
      copy:
        src: intermediate.crt.vault
        dest: /etc/ssl/certs/InCommon-chain.crt 
