---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install Apache2
      package:
        name: "{{ apache_package_name }}"
        state: installed
        update_cache: true

    - name: Enable mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify:
        - Restart Apache2

    - name: Enable mod_ssl
      apache2_module:
        name: ssl
        state: present
      notify:
        - Restart Apache2

    - name: Install mod_wsgi
      package:
        name: "{{ mod_wsgi_package_name }}"
        state: installed
        update_cache: true

    - name: Enable mod_wsgi
      apache2_module:
        name: wsgi
        state: present
      notify:
        - Restart Apache2

  handlers:
    - name: Restart Apache2
      service:
        name: "{{ apache_service_name }}" 
        state: restarted
