---
- hosts: local
  connection: local
  tasks:
    - name: Include variables
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution }}-{{ansible_distribution_major_version | int }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/default.yml"
- import_playbook: apache2.yml
- import_playbook: memcached.yml
- import_playbook: mongodb.yml
- import_playbook: users.yml
- import_playbook: groups.yml
- import_playbook: system-reqs.yml
- import_playbook: unplatform.yml
- import_playbook: qbank.yml
- import_playbook: webapps.yml
- import_playbook: apache-ssl-files.yml
# Handled by Puppet / IS&T
# - import_playbook: apache-config.yml
