---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install memcached service
      package:
        name: "{{ memcached_package_name }}"
        state: installed
        update_cache: yes
      notify:
        - Restart Memcached

    handlers:
      - name: Restart Memcached
        service:
          name: "{{ memcached_service_name }}" 
          state: restarted
