---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install memcached service
      apt:
        name: "{{ memcached_package_name }}"
        state: installed
        update_cache: yes
