---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Import MongoDB public GPG key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
      when: ansible_os_family == "Debian"
    - name: Add MongoDB repository into sources list
      apt_repository:
        repo: deb https://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/3.6 multiverse
        state: present
      when: ansible_os_family == "Debian"
    - name: Add MongoDB repository
      template:
        src: mongo-repo.j2
        dest: /etc/yum.repos.d/mongodb-org-3.6.repo
      when: ansible_os_family == "RedHat"
    - name: Install MongoDB
      package:
        name: "{{ mongo_package_name }}"
        state: installed
        update_cache: yes
      notify:
        - Restart MongoDB
    - name: Copy MongoDB conf file
      copy:
        src: mongod.conf.vault
        dest: /etc/mongod.conf
      notify:
        - Restart MongoDB

    handlers:
      - name: Restart MongoDB
        service:
          name: "{{ mongo_service_name }}"
          state: restarted
