---
# Install and manage qbank build as local user
- hosts: local
  connection: local
  tasks:
    - name: Install QBank requirements
      pip:
        requirements: /var/www/webapps/qbank/requirements.txt
        virtualenv: "/home/{{ ansible_user }}/.virtualenvs/qbank"
        virtualenv_python: python2.7
        state: forcereinstall
