---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Give Apache group write access to virtualenv
      become: yes
      become_user: root
      file:
        dest: /var/www/webapps/CLIx/unplatform/unplatform.sqlite3
        mode: g+w
        group: "{{ apache_group_name }}"
