---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Clone QBank
      git:
        repo: https://github.com/CLIxIndia-Dev/qbank-lite.git
        dest: /var/www/webapps/qbank
        version: unplatform-dev-app-1
    - name: Change QBank directory owner and group
      file:
        dest: /var/www/webapps/qbank
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        recurse: yes
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
    - name: Make virtualenv directory
      file:
        dest: /usr/local/.virtualenvs/qbank
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        mode: g+w
        state: directory
    - name: Create qbank JSON file directory
      file:
        dest: /var/www/html/qbank/webapps
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        mode: g+w
        state: directory
- import_playbook: qbank-install.yml
- import_playbook: qbank-apache-ssl.yml
