---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install libxml2-dev
      apt:
        name: libxml2-dev
        state: installed
        update_cache: true
    - name: Install libxslt1-dev
      apt:
        name: libxslt1-dev
        state: installed
        update_cache: true
    - name: Install libssl-dev
      apt:
        name: libssl-dev
        state: installed
        update_cache: true
    - name: Install libffi-dev
      apt:
        name: libffi-dev
        state: installed
        update_cache: true
    - name: Install python-dev
      apt:
        name: python-dev
        state: installed
        update_cache: true
