---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install C compiler
      package:
        name: "{{ c_compiler_package_name }}"
        state: installed
        update_cache: true
    - name: Install libxml2-dev
      package:
        name: "{{ libxml2_package_name }}"
        state: installed
        update_cache: true
    - name: Install libxslt1-dev
      package:
        name: "{{ libxslt1_package_name }}"
        state: installed
        update_cache: true
    - name: Install libssl-dev
      package:
        name: "{{ libssl_package_name }}"
        state: installed
        update_cache: true
    - name: Install libffi-dev
      package:
        name: "{{ libffi_package_name }}"
        state: installed
        update_cache: true
    - name: Install python-dev
      package:
        name: "{{ python_package_name }}"
        state: installed
        update_cache: true
    - name: Install zip
      package:
        name: "{{ zip_package_name }}"
        state: installed
        update_cache: true
