---
- hosts: local
  connection: local
  tasks:
    - name: Clear out old static files
      file:
        path: /var/www/html/unplatform/static/
        state: absent
    - name: Copy Unplatform static files
      synchronize:
        src: /var/www/webapps/unplatform/bundle/static/
        dest: /var/www/html/unplatform/static
    - name: Copy Unplatform module tool wrapper files
      synchronize:
        src: /var/www/webapps/unplatform/bundle/modules/
        dest: /var/www/html/unplatform/modules
