---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Clone Unplatform2
      git:
        repo: https://github.com/CLIxIndia-Dev/unplatform_v2.git
        dest: /var/www/webapps/unplatform
        version: deploy
    - name: Create Unplatform2 static/ui directory
      file:
        path: /var/www/webapps/unplatform/static/ui
        state: directory
    - name: Change Unplatform2 directory owner and group
      file:
        dest: /var/www/webapps/unplatform
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        mode: g+w
        recurse: yes
    - name: Create Unplatform2 html static directory
      file:
        path: /var/www/html/unplatform/static
        state: directory
    - name: Change Unplatform2 html static directory owner and group
      file:
        dest: /var/www/html/unplatform
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        recurse: yes
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: present
    - name: Make virtualenv home
      file:
        dest: /usr/local/.virtualenvs
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        mode: g+w
        state: directory
    - name: Make unplatform virtualenv directory
      file:
        dest: /usr/local/.virtualenvs/unplatform
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        mode: g+w
        state: directory
    - name: Create data store directory
      file:
        dest: /var/www/webapps/CLIx/unplatform
        owner: "{{ ansible_user }}"
        group: "{{ apache_group_name }}"
        mode: g+w
        state: directory
- import_playbook: unplatform-install.yml
- import_playbook: unplatform-cleanup.yml
- import_playbook: unplatform-apache.yml
- import_playbook: unplatform-apache-ssl.yml
- import_playbook: unplatform-copy-static.yml
