---
- hosts: local
  connection: local
  become: yes
  become_user: root
  vars:
    http_port: 443 
    domain: unplatform.mit.edu
    log: unplatform.mit.edu
    admin: clix-tech@mit.edu
    app_name: unplatform 
  tasks:
    - name: Create HTTP site file
      template:
        src: vhost_ssl.conf.j2
        dest: "/etc/apache2/sites-available/{{ domain }}-ssl.conf"
