---
- hosts: local
  connection: local
  tasks:
    - name: Copy Unplatform static files
      synchronize:
        src: /var/www/webapps/unplatform/bundle/static/
        dest: /var/www/html/unplatform/static
