---
- hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Adding existing user '{{ ansible_user }}' to apache group
      user:
        name: "{{ ansible_user }}"
        groups: "{{ apache_group_name }}"
        append: yes
